import os
import subprocess
from pathlib import Path
from datetime import datetime

def assemble_episode(audio_dir, output_file="podcast/output/episode.mp3", metadata=None):
    """
    Assembles audio clips from a directory into a single MP3 file.
    
    Args:
        audio_dir (str): Directory containing .mp3 segments.
        output_file (str): Path for the final output file.
        metadata (dict): Metadata for ID3 tags (title, artist, etc.).
    
    Returns:
        str: Path to the generated file, or None if failed.
    """
    input_path = Path(audio_dir)
    output_path = Path(output_file)
    output_path.parent.mkdir(parents=True, exist_ok=True)
    
    # 1. List audio files
    # Assuming files are named line_000.mp3, line_001.mp3, etc.
    files = sorted([f for f in input_path.glob("*.mp3")])
    
    if not files:
        print(f"No audio files found in {audio_dir}")
        return None
        
    print(f"Found {len(files)} audio segments to assemble.")
    
    # 2. Create file list for ffmpeg
    list_file_path = input_path / "files.txt"
    with open(list_file_path, "w") as f:
        for file_path in files:
            # escaped_path = str(file_path.absolute()).replace("'", "'\\''")
            f.write(f"file '{file_path.absolute()}'\n")
            
    # 3. Build ffmpeg command
    # ffmpeg -f concat -safe 0 -i files.txt -c copy -metadata title="..." output.mp3
    cmd = [
        "ffmpeg",
        "-f", "concat",
        "-safe", "0",
        "-i", str(list_file_path.absolute()),
        "-c", "copy",
        "-y", # Overwrite output
    ]
    
    # Add metadata if provided
    if metadata:
        if "title" in metadata:
            cmd.extend(["-metadata", f"title={metadata['title']}"])
        if "artist" in metadata:
            cmd.extend(["-metadata", f"artist={metadata['artist']}"])
        if "album" in metadata:
            cmd.extend(["-metadata", f"album={metadata['album']}"])
        if "description" in metadata:
             cmd.extend(["-metadata", f"comment={metadata['description']}"]) # 'comment' is often used for description
             
    cmd.append(str(output_path.absolute()))
    
    print(f"Running ffmpeg command: {' '.join(cmd)}")
    
    try:
        subprocess.run(cmd, check=True, stdout=subprocess.PIPE, stderr=subprocess.PIPE)
        print(f"Successfully created episode: {output_file}")
        
        # Cleanup list file
        list_file_path.unlink()
        
        return str(output_path)
    except subprocess.CalledProcessError as e:
        print(f"Error running ffmpeg: {e}")
        print(f"Detailed error: {e.stderr.decode()}")
        return None
    except Exception as e:
        print(f"Unexpected error during assembly: {e}")
        return None

if __name__ == "__main__":
    # Test execution
    test_metadata = {
        "title": f"Listen Later Test - {datetime.now().strftime('%Y-%m-%d')}",
        "artist": "Listen Later AI",
        "album": "Stash Podcast",
        "description": "A test episode generated by the assembly script."
    }
    assemble_episode("podcast/temp_audio", "podcast/output/test_episode.mp3", test_metadata)
